language: cpp

env:
  global:
    # Ubuntu version
    - LINUX_DIST=bionic
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps

matrix:
  include:
    - os: linux
      dist: bionic
      sudo: true
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages: &precise_latest_boost_packages
            - gcc-7
            - g++-7
            - lcov
            - libgtest-dev
            - cmake

# before_install:
#     # Combine global build options with OS/compiler-dependent options
#     - export CMAKE_OPTIONS=${CMAKE_OPTIONS}" "${ENV_CMAKE_OPTIONS}
#     - export CXX_FLAGS=${CXX_FLAGS}" "${ENV_CXX_FLAGS}

install:
    - echo ${PATH}
    - echo ${CXX}
    - ${CXX} --version
    - ${CXX} -v
    - sudo pip install codecov

    - mkdir -p ${DEPS_DIR}/arrayfire
    - wget https://arrayfire.s3.amazonaws.com/3.6.4/ArrayFire-v3.6.4_Linux_x86_64.sh -O /${DEPS_DIR}/ArrayFire-v3.6.4_Linux_x86_64.sh
    - sudo sh ${DEPS_DIR}/ArrayFire-v3.6.4_Linux_x86_64.sh --include-subdir --prefix=/opt
    - sudo sh -c "echo /opt/arrayfire/lib64 > /etc/ld.so.conf.d/arrayfire.conf"
    - sudo ldconfig

    - cd /usr/src/gtest
    - sudo mkdir build
    - cd build/
    - sudo cmake ..
    - sudo make
    - sudo cp libgtest*.a /usr/local/lib
    - cd ${TRAVIS_BUILD_DIR}

script:
    ############################################################################
    # Build main and tests
    ############################################################################
      - sudo mkdir -p build
      - sudo mkdir -p bin
      - cd build
      - sudo cmake -DCMAKE_BUILD_TYPE=Coverage -DBUILD_TESTS=ON -DBUILD_CUDA=OFF ..
      - sudo make MLKIT_TEST_COV

after_success:
    - codecov -t 585bde79-970a-4715-b848-bdb5081cdbf7 -X gcov
